### ISSUE TITLE
Nothing happened after running this command in the terminal of MacOs

### ISSUE THREAD

**Issue by LucasIsGood** [SpotX-CLI/SpotX-Mac#18]
<img width="1440" alt="截屏2022-10-14 17 11 35 1" src="https://user-images.githubusercontent.com/56297860/195809647-d411bdf9-2db5-47f1-85a8-b7b12a20d352.png">

**Comment by jetfir3** [comment]
I'm unable to replicate this behavior. But the script does not need to be piped from curl to bash and can "run locally" -- although this would also require always checking for script updates which is not ideal.

But just to test, what happens if you do the following:
1. `curl -O https://raw.githubusercontent.com/SpotX-CLI/SpotX-Mac/main/install.sh`
2. `chmod +x install.sh`
3. `bash install.sh`

**Comment by amd64fox** [comment]
@jetfir3 
fix command to uninstall

**Comment by LucasIsGood** [comment]
> I'm unable to replicate this behavior. But the script does not need to be piped from curl to bash and can "run locally" -- although this would also require always checking for script updates which is not ideal.
> 
> But just to test, what happens if you do the following:
> 
> 1. `curl -O https://raw.githubusercontent.com/SpotX-CLI/SpotX-Mac/main/install.sh`
> 2. `chmod +x install.sh`
> 3. `bash install.sh`

Oh my god bro it worked!! Spotify has no banner now and ads.Thanks for your reply.
<img width="1440" alt="截屏2022-10-19 14 41 22" src="https://user-images.githubusercontent.com/56297860/196616139-1ff87962-e52f-46d6-aefe-f8189c56b3a9.png">

<img width="1440" alt="截屏2022-10-19 14 41 40" src="https://user-images.githubusercontent.com/56297860/196616177-149a17a8-7968-4b42-adf1-149ad267c287.png">

**Comment by Nuzair46** [comment]
@LucasIsGood , something completely unrelated.
which app is that kitty icon in menu bar?

**Comment by jetfir3** [comment]
> 
> Oh my god bro it worked!! Spotify has no banner now and ads.Thanks for your reply. 

@LucasIsGood 
Nice, glad it at least works for you with that route. Still not ideal as the script is constantly evolving and running an up-to-date script should usually be preferred.

Can you test the following command in your terminal and let us know if you get any output this time (versus your initial screenshot which seemed to do nothing at all):
`bash <(curl -sL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Mac/main/install.sh)`
and if still nothing...
`bash <(curl https://raw.githubusercontent.com/SpotX-CLI/SpotX-Mac/main/install.sh)`

Thanks.

**Comment by LucasIsGood** [comment]
> @LucasIsGood , something completely unrelated.
> which app is that kitty icon in menu bar?

clash ,without it you can't see my comments

**Comment by LucasIsGood** [comment]
@jetfir3 My spotify shows ads again after getting up in the morning.I tried your first command and the second command at the same time.I don't know what the difference between them laugh out loud (my bad linux command learning).It worked using the first command.I don't know if it works with the second one.The result is in my screenshot.
<img width="1440" alt="截屏2022-10-20 10 54 19" src="https://user-images.githubusercontent.com/56297860/196845854-57461779-d5d5-4e52-8fc8-bcde59da2a32.png">

**Comment by jetfir3** [comment]
> My spotify shows ads again after getting up in the morning.I tried your first command and the second command at the same time.

It's likely that Spotify had updated itself, the latest 1.1.96 has been rolling out. 
Based on the output in your screenshots, the first time you ran the "new" command SpotX treated things as if it was the first time running it. No previous patch detected which indicates an update to the Spotify client is likely. 

SpotX needs to be run any time the Spotify client is updated. SpotX also has the option to block updates to avoid this type of surprise but updating manually would then also be needed (until we build in updates to SpotX itself). 


>It worked using the first command.I don't know if it works with the second one.
Perfect. Thanks for testing those out. According to your screenshot, both commands worked. The output in the second command changed because SpotX detected it had already patched the current installed version of Spotify.

It looks like we now have a resolution to the issue. I'll be making a pull request to address this.

**Comment by jetfir3** [comment]
@LucasIsGood 
SpotX patches Spotify but the patch is removed if the Spotify client is updated.  If Spotify is updated, SpotX needs to be run again. 

You can block updates using SpotX and the `-u` flag. See the readme for more info on flags and features. 
`bash <(curl -sL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Mac/main/install.sh) -u`
